server:
  port: 8080
spring:
  application:
    name: Notification-Manager
  kafka:
    bootstrap-servers: localhost:9092
    ## Kafka consumer config
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer



## SMS API Config
fast2sms:
  api:
    key: Oin6Qf9Yg4Va2tlsqhTku3IDdFMvAJ8jmZPHpXrbRUeBWwN5ESK9mIaxMCbLfq5PFuGoNJ1yWQ7gpZjR
  base:
    uri: https://www.fast2sms.com/dev
cable:
  event-types:
    USER_REGISTRATION_EVENT: user-registration-topic
    FORGOT_PASSWORD_EVENT: forgot-password-topic
    RESET_PASSWORD_EVENT: forgot-password-topic
    OTP_VERIFICATION_EVENT: otp-verification-topic